spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: Amit@1995
    driver-class-name: com.mysql.cj.jdbc.Driver

  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name:  CRUD-OPERATIONS-VALIDATION
     
server:
  port: 9191